name: keypoint_moseq

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytables
  - openblas
  - numpy=1.23.5
  - conda-forge::jax=0.3.22
  - conda-forge::jaxlib=0.3.22=*cpu*
  - pip
  - pip:
    - "keypoint-moseq"
    - jupyterlab
    - etils==1.5.2